### ISSUE TITLE
'undefined symbol: crypt_r' when running the app, in a VM

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [DoTheEvo/ANGRYsearch#71]
```
testing@testing-VirtualBox:~/Downloads/Angry/ANGRYsearch-master$ angrysearch
Traceback (most recent call last):
  File "/usr/bin/angrysearch", line 34, in <module>
    import PyQt5.QtGui as Qg
ImportError: /usr/lib/x86_64-linux-gnu/VBoxOGLcrutil.so: undefined symbol: crypt_r
$ angrysearch --version
Traceback (most recent call last):
  File "/usr/bin/angrysearch", line 34, in <module>
    import PyQt5.QtGui as Qg
ImportError: /usr/lib/x86_64-linux-gnu/VBoxOGLcrutil.so: undefined symbol: crypt_r
```

Running Virtual Box, with guest Linux Mint Cinnamon 19.1 x64, host Windows 8.1 x64. Version of AngrySearch: the one I've download as a zip, just now, from here on Github.

**Comment by zdenop** [comment]
This is not ANGRYsearch error, but Virtual Box.

**Comment by LinuxOnTheDesktop** [comment]
[Ah yes](https://www.virtualbox.org/ticket/18324). Thanks.
