### ISSUE TITLE
Unable to start: database disk image is malformed

### ISSUE THREAD

**Issue by onidev** [DoTheEvo/ANGRYsearch#85]
Hi,
It was working fine, but for some unknown reason it doesn't want to start anymore.

If I run it from the terminal I have this trace:
```autodetected file manager: dolphin
Traceback (most recent call last):
  File "/usr/bin/angrysearch", line 1723, in <module>
    ui = Gui_MainWindow()
  File "/usr/bin/angrysearch", line 650, in __init__
    self.init_GUI()
  File "/usr/bin/angrysearch", line 893, in init_GUI
    self.show_first_500()
  File "/usr/bin/angrysearch", line 1179, in show_first_500
    cur.execute('''PRAGMA user_version;''')
sqlite3.DatabaseError: database disk image is malformed```

**Comment by onidev** [comment]
Fixed it manually by removing the file:
~/.cache/angrysearch/angry_database.db

But it would be better to add an option that asks to delete the database if there is this error at launch.
